
/*
 * Copyright (c) 2014. Axetta LLC. All Rights Reserved.
 */

package ru.axetta.ecafe.processor.core.service.regularPaymentService.kzn_bankkazani.ru.bankofkazan;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SchoolCardService", targetNamespace = "http://bankofkazan.ru/", wsdlLocation = "http://91.226.171.43:7001/SchoolCardWS/SchoolCardPort?wsdl")
public class SchoolCardService
    extends Service
{

    private final static URL SCHOOLCARDSERVICE_WSDL_LOCATION;
    private final static WebServiceException SCHOOLCARDSERVICE_EXCEPTION;
    private final static QName SCHOOLCARDSERVICE_QNAME = new QName("http://bankofkazan.ru/", "SchoolCardService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://91.226.171.43:7001/SchoolCardWS/SchoolCardPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SCHOOLCARDSERVICE_WSDL_LOCATION = url;
        SCHOOLCARDSERVICE_EXCEPTION = e;
    }

    public SchoolCardService() {
        super(__getWsdlLocation(), SCHOOLCARDSERVICE_QNAME);
    }
    //
    //public SchoolCardService(WebServiceFeature... features) {
    //    super(__getWsdlLocation(), SCHOOLCARDSERVICE_QNAME, new AddressingFeature());
    //}

    public SchoolCardService(URL wsdlLocation) {
        super(wsdlLocation, SCHOOLCARDSERVICE_QNAME);
    }

    //public SchoolCardService(URL wsdlLocation, WebServiceFeature... features) {
    //    super(wsdlLocation, SCHOOLCARDSERVICE_QNAME, features);
    //}

    public SchoolCardService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    //public SchoolCardService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    //    super(wsdlLocation, serviceName, features);
    //}

    /**
     * 
     * @return
     *     returns SchoolCard
     */
    @WebEndpoint(name = "SchoolCardPort")
    public SchoolCard getSchoolCardPort() {
        return super.getPort(new QName("http://bankofkazan.ru/", "SchoolCardPort"), SchoolCard.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SchoolCard
     */
    @WebEndpoint(name = "SchoolCardPort")
    public SchoolCard getSchoolCardPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bankofkazan.ru/", "SchoolCardPort"), SchoolCard.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SCHOOLCARDSERVICE_EXCEPTION!= null) {
            throw SCHOOLCARDSERVICE_EXCEPTION;
        }
        return SCHOOLCARDSERVICE_WSDL_LOCATION;
    }

}
