
/*
 * Copyright (c) 2014. Axetta LLC. All Rights Reserved.
 */

package ru.axetta.ecafe.processor.core.service.regularPaymentService.kzn_bankkazani.ru.bankofkazan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SchoolCard", targetNamespace = "http://bankofkazan.ru/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SchoolCard {


    /**
     * 
     * @param requestex
     * @return
     *     returns ru.bankofkazan.AsynchronousPaymentResponse
     */
    @WebMethod(operationName = "AsynchronousPayment")
    @WebResult(name = "AsynchronousPaymentResponse", targetNamespace = "http://bankofkazan.ru/", partName = "responseex")
    @Action(input = "http://bankofkazan.ru/SchoolCard/AsynchronousPaymentRequest", output = "http://bankofkazan.ru/SchoolCard/AsynchronousPaymentResponse")
    public AsynchronousPaymentResponse asynchronousPayment(
            @WebParam(name = "AsynchronousPaymentRequest", targetNamespace = "http://bankofkazan.ru/",
                    partName = "requestex") AsynchronousPaymentRequest requestex);

}
