/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.iteco.emias.kafka.Request;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.LocalDate;
import java.util.Objects;

/**
 * Данные о периоде освобождения от посещения ОО
 */
@Schema(description = "Данные о периоде освобождения от посещения ОО")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-28T22:45:51.033+03:00[Europe/Moscow]")
public class PersonExemptionItem {
  @SerializedName("from")
  private LocalDate from = null;

  @SerializedName("to")
  private LocalDate to = null;

  @SerializedName("hazard_level_id")
  private Integer hazardLevelId = null;

  public PersonExemptionItem from(LocalDate from) {
    this.from = from;
    return this;
  }

   /**
   * Дата начала периода
   * @return from
  **/
  @Schema(required = true, description = "Дата начала периода")
  public LocalDate getFrom() {
    return from;
  }

  public void setFrom(LocalDate from) {
    this.from = from;
  }

  public PersonExemptionItem to(LocalDate to) {
    this.to = to;
    return this;
  }

   /**
   * Дата окончания периода
   * @return to
  **/
  @Schema(required = true, description = "Дата окончания периода")
  public LocalDate getTo() {
    return to;
  }

  public void setTo(LocalDate to) {
    this.to = to;
  }

  public PersonExemptionItem hazardLevelId(Integer hazardLevelId) {
    this.hazardLevelId = hazardLevelId;
    return this;
  }

   /**
   * Уровень опасности: 0 - нейтральный 1 - высокий 
   * @return hazardLevelId
  **/
  @Schema(required = true, description = "Уровень опасности: 0 - нейтральный 1 - высокий ")
  public Integer getHazardLevelId() {
    return hazardLevelId;
  }

  public void setHazardLevelId(Integer hazardLevelId) {
    this.hazardLevelId = hazardLevelId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonExemptionItem personExemptionItem = (PersonExemptionItem) o;
    return Objects.equals(this.from, personExemptionItem.from) &&
        Objects.equals(this.to, personExemptionItem.to) &&
        Objects.equals(this.hazardLevelId, personExemptionItem.hazardLevelId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to, hazardLevelId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonExemptionItem {\n");
    
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    hazardLevelId: ").append(toIndentedString(hazardLevelId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
