/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.iteco.emias.kafka.Request;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;
import java.util.Objects;

/**
 * Данные об освобождении от посещения ОО
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class PersonExemption {
  @SerializedName("id")
  private String id = null;

  @SerializedName("person_id")
  private String person_id = null;

  @SerializedName("items")
  private List<PersonExemptionItem> items = null;

  @SerializedName("reason")
  private Integer reason = null;

  @SerializedName("created_at")
  private String created_at = null;

   /**
   * Идентификатор сообщения
   * @return id
  **/
  @Schema(required = true, description = "Идентификатор сообщения")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

   /**
   * Идентификатор персоны МЭШ.Контингента
   * @return personId
  **/
  @Schema(required = true, description = "Идентификатор персоны МЭШ.Контингента")
  public String getPerson_id() {
    return person_id;
  }

  public void setPerson_id(String person_id) {
    this.person_id = person_id;
  }

   /**
   * Данные о периодах освобождения
   * @return items
  **/
  @Schema(description = "Данные о периодах освобождения")
  public List<PersonExemptionItem> getItems() {
    return items;
  }

  public void setItems(List<PersonExemptionItem> items) {
    this.items = items;
  }

   /**
   * Основание: 1 - Справка 095/у 2 - Рекомендация по освобождению от посещения ОУ 
   * @return reason
  **/
  @Schema(required = true, description = "Основание: 1 - Справка 095/у 2 - Рекомендация по освобождению от посещения ОУ ")
  public Integer getReason() {
    return reason;
  }

  public void setReason(Integer reason) {
    this.reason = reason;
  }

   /**
   * Дата и время события
   * @return createdAt
  **/
  @Schema(required = true, description = "Дата и время события")
  public String getCreated_at() {
    return created_at;
  }

  public void setCreated_at(String created_at) {
    this.created_at = created_at;
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, person_id, items, reason, created_at);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonExemption {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    personId: ").append(toIndentedString(person_id)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(created_at)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
