/*
 * 
 * 
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.iteco.emias.kafka.Request;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Данные о периоде освобождения от посещения ОО
 */
@Schema(description = "Данные о периоде освобождения от посещения ОО")
@JsonIgnoreProperties(ignoreUnknown = true)
public class PersonExemptionItem {
  @SerializedName("from")
  private String from = null;

  @SerializedName("to")
  private String to = null;

  @SerializedName("hazard_level_id")
  private Integer hazard_level_id = null;

   /**
   * Дата начала периода
   * @return from
  **/
  @Schema(required = true, description = "Дата начала периода")
  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

   /**
   * Дата окончания периода
   * @return to
  **/
  @Schema(required = true, description = "Дата окончания периода")
  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

   /**
   * Уровень опасности: 0 - нейтральный 1 - высокий 
   * @return hazardLevelId
  **/
  @Schema(required = true, description = "Уровень опасности: 0 - нейтральный 1 - высокий ")
  public Integer getHazard_level_id() {
    return hazard_level_id;
  }

  public void setHazard_level_id(Integer hazard_level_id) {
    this.hazard_level_id = hazard_level_id;
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to, hazard_level_id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonExemptionItem {\n");
    
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    hazardLevelId: ").append(toIndentedString(hazard_level_id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
