
package ru.axetta.soap.smev.pfr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServicePFR", targetNamespace = "http://service.pfr.socit.ru")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicePFR {


    /**
     * 
     * @param message
     * @param messageData
     */
    @WebMethod(operationName = "Process")
    @RequestWrapper(localName = "Process", targetNamespace = "http://service.pfr.socit.ru", className = "ru.axetta.soap.smev.pfr.BaseMessageType")
    @ResponseWrapper(localName = "ProcessResponse", targetNamespace = "http://service.pfr.socit.ru", className = "ru.axetta.soap.smev.pfr.BaseMessageType")
    public void process(
        @WebParam(name = "Message", targetNamespace = "http://smev.gosuslugi.ru/rev111111", mode = WebParam.Mode.INOUT)
        Holder<MessageType> message,
        @WebParam(name = "MessageData", targetNamespace = "http://smev.gosuslugi.ru/rev111111", mode = WebParam.Mode.INOUT)
        Holder<MessageDataType> messageData);

}
