
package ru.axetta.ecafe.processor.web.istkservice.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IstkController", targetNamespace = "http://soap.services.school.istk.axetta.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IstkController {


    /**
     * 
     * @param options
     * @return
     *     returns ru.axetta.ecafe.processor.web.istkservice.client.BaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveSchoolsGamePermissions", targetNamespace = "http://soap.services.school.istk.axetta.ru/", className = "ru.axetta.ecafe.processor.web.istkservice.client.SaveSchoolsGamePermissions")
    @ResponseWrapper(localName = "saveSchoolsGamePermissionsResponse", targetNamespace = "http://soap.services.school.istk.axetta.ru/", className = "ru.axetta.ecafe.processor.web.istkservice.client.SaveSchoolsGamePermissionsResponse")
    public BaseResult saveSchoolsGamePermissions(
        @WebParam(name = "options", targetNamespace = "")
        List<Pair> options);

    /**
     * 
     * @return
     *     returns ru.axetta.ecafe.processor.web.istkservice.client.SchoolListResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSchools", targetNamespace = "http://soap.services.school.istk.axetta.ru/", className = "ru.axetta.ecafe.processor.web.istkservice.client.GetSchools")
    @ResponseWrapper(localName = "getSchoolsResponse", targetNamespace = "http://soap.services.school.istk.axetta.ru/", className = "ru.axetta.ecafe.processor.web.istkservice.client.GetSchoolsResponse")
    public SchoolListResult getSchools();

}
