
package ru.axetta.ecafe.processor.web.istkservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IstkController", targetNamespace = "http://soap.services.school.istk.axetta.ru/", wsdlLocation = "http://localhost:8080/istk-school/soap/client?wsdl")
public class IstkController_Service
    extends Service
{

    private final static URL ISTKCONTROLLER_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ru.axetta.ecafe.processor.web.istkservice.client.IstkController_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ru.axetta.ecafe.processor.web.istkservice.client.IstkController_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/istk-school/soap/client?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/istk-school/soap/client?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ISTKCONTROLLER_WSDL_LOCATION = url;
    }

    public IstkController_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IstkController_Service() {
        super(ISTKCONTROLLER_WSDL_LOCATION, new QName("http://soap.services.school.istk.axetta.ru/", "IstkController"));
    }

    /**
     * 
     * @return
     *     returns IstkController
     */
    @WebEndpoint(name = "IstkControllerPort")
    public IstkController getIstkControllerPort() {
        return super.getPort(new QName("http://soap.services.school.istk.axetta.ru/", "IstkControllerPort"), IstkController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IstkController
     */
    @WebEndpoint(name = "IstkControllerPort")
    public IstkController getIstkControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.services.school.istk.axetta.ru/", "IstkControllerPort"), IstkController.class, features);
    }

}
