
package ru.axetta.ecafe.processor.dashboard;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DashboardServiceWSService", targetNamespace = "http://dashboard.processor.ecafe.axetta.ru/", wsdlLocation = "http://localhost:8080/processor/soap/dashboard?wsdl")
public class DashboardServiceWSService
    extends Service
{

    private final static URL DASHBOARDSERVICEWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ru.axetta.ecafe.processor.dashboard.DashboardServiceWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ru.axetta.ecafe.processor.dashboard.DashboardServiceWSService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/processor/soap/dashboard?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/processor/soap/dashboard?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DASHBOARDSERVICEWSSERVICE_WSDL_LOCATION = url;
    }

    public DashboardServiceWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DashboardServiceWSService() {
        super(DASHBOARDSERVICEWSSERVICE_WSDL_LOCATION, new QName("http://dashboard.processor.ecafe.axetta.ru/", "DashboardServiceWSService"));
    }

    /**
     * 
     * @return
     *     returns DashboardService
     */
    @WebEndpoint(name = "DashboardServiceWSPort")
    public DashboardService getDashboardServiceWSPort() {
        return super.getPort(new QName("http://dashboard.processor.ecafe.axetta.ru/", "DashboardServiceWSPort"), DashboardService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DashboardService
     */
    @WebEndpoint(name = "DashboardServiceWSPort")
    public DashboardService getDashboardServiceWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dashboard.processor.ecafe.axetta.ru/", "DashboardServiceWSPort"), DashboardService.class, features);
    }

}
