openapi: 3.0.1
components:
  schemas:
    PersonExemptionItem:
      description: Данные о периоде освобождения от посещения ОО
      required:
        - from
        - to
        - state
        - hazard_level_id
        - reason
      type: object
      properties:
        from:
          description: Дата начала периода
          type: string
          format: date
        to:
          description: Дата окончания периода
          type: string
          format: date
        hazard_level_id:
          type: integer
          description: |
            Уровень опасности:
            0 - нейтральный
            1 - высокий
    PersonExemption:
      description: Данные об освобождении от посещения ОО
      required:
        - id
        - person_id
        - created_at
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор события
        person_id:
          type: string
          format: UUID
          description: Идентификатор персоны МЭШ.Контингента
        items:
          description: Данные о периодах освобождения
          type: array
          items:
            $ref: '#/components/schemas/PersonExemptionItem'
        reason:
          type: integer
          description: |
            Основание:
            1 - Справка 095/у
            2 - Рекомендация по освобождению от посещения ОУ
        created_at:
          type: string
          format: "date-time"
          description: Дата и время события
paths: {}