
/*
 * Copyright (c) 2013. Axetta LLC. All Rights Reserved.
 */

package ru.axetta.soap.smev;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MsgExampleService", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/", wsdlLocation = "file:/C:/0000/smevservice/SID0003022_1.wsdl")
public class MsgExampleService
    extends Service
{

    private final static URL MSGEXAMPLESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ru.axetta.soap.smev.MsgExampleService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ru.axetta.soap.smev.MsgExampleService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/0000/smevservice/SID0003022_1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/0000/smevservice/SID0003022_1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MSGEXAMPLESERVICE_WSDL_LOCATION = url;
    }

    public MsgExampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MsgExampleService() {
        super(MSGEXAMPLESERVICE_WSDL_LOCATION, new QName("http://smev.gosuslugi.ru/MsgExample/", "MsgExampleService"));
    }

    /**
     * 
     * @return
     *     returns MsgExamplePort
     */
    @WebEndpoint(name = "MsgExamplePort")
    public MsgExamplePort getMsgExamplePort() {
        return super.getPort(new QName("http://smev.gosuslugi.ru/MsgExample/", "MsgExamplePort"), MsgExamplePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MsgExamplePort
     */
    @WebEndpoint(name = "MsgExamplePort")
    public MsgExamplePort getMsgExamplePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://smev.gosuslugi.ru/MsgExample/", "MsgExamplePort"), MsgExamplePort.class, features);
    }

}
