
/*
 * Copyright (c) 2013. Axetta LLC. All Rights Reserved.
 */

package ru.axetta.ecafe.processor.web.partner.integra.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ClientRoomControllerWSService",
        targetNamespace = "http://soap.integra.partner.web.processor.ecafe.axetta.ru/",
        wsdlLocation = "http://172.18.16.14:8080/processor/soap/client?wsdl")
public class ClientRoomControllerWSService
    extends Service
{

    private final static URL CLIENTROOMCONTROLLERWSSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://172.18.16.14:8080/processor/soap/client?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CLIENTROOMCONTROLLERWSSERVICE_WSDL_LOCATION = url;
    }

    public ClientRoomControllerWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientRoomControllerWSService() {
        super(CLIENTROOMCONTROLLERWSSERVICE_WSDL_LOCATION, new QName("http://soap.integra.partner.web.processor.ecafe.axetta.ru/", "ClientRoomControllerWSService"));
    }

    /**
     * 
     * @return
     *     returns ClientRoomController
     */
    @WebEndpoint(name = "ClientRoomControllerWSPort")
    public ClientRoomController getClientRoomControllerWSPort() {
        return (ClientRoomController)super.getPort(new QName("http://soap.integra.partner.web.processor.ecafe.axetta.ru/", "ClientRoomControllerWSPort"), ClientRoomController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientRoomController
     */
    @WebEndpoint(name = "ClientRoomControllerWSPort")
    public ClientRoomController getClientRoomControllerWSPort(WebServiceFeature... features) {
        return (ClientRoomController)super.getPort(new QName("http://soap.integra.partner.web.processor.ecafe.axetta.ru/", "ClientRoomControllerWSPort"), ClientRoomController.class, features);
    }

}
