/*
 * Copyright (c) 2020. Axetta LLC. All Rights Reserved.
 */

/*
 * API МЭШ.Контингент
 * Описание REST API МЭШ.Контингент
 *
 * OpenAPI spec version: 0.0.1
 * Contact: fixme@ktelabs.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.iteco.client.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
/**
 * Элемент фильтра
 */
@Schema(description = "Элемент фильтра")
public class FilterCondition {
  @SerializedName("and")
  private List<FilterCondition> and = null;

  @SerializedName("or")
  private List<FilterCondition> or = null;

  @SerializedName("field")
  private String field = null;

  @SerializedName("op")
  private String op = null;

  @SerializedName("value")
  private Object value = null;

  public FilterCondition and(List<FilterCondition> and) {
    this.and = and;
    return this;
  }

  public FilterCondition addAndItem(FilterCondition andItem) {
    if (this.and == null) {
      this.and = new ArrayList<FilterCondition>();
    }
    this.and.add(andItem);
    return this;
  }

   /**
   * Get and
   * @return and
  **/
  @Schema(description = "")
  public List<FilterCondition> getAnd() {
    return and;
  }

  public void setAnd(List<FilterCondition> and) {
    this.and = and;
  }

  public FilterCondition or(List<FilterCondition> or) {
    this.or = or;
    return this;
  }

  public FilterCondition addOrItem(FilterCondition orItem) {
    if (this.or == null) {
      this.or = new ArrayList<FilterCondition>();
    }
    this.or.add(orItem);
    return this;
  }

   /**
   * Get or
   * @return or
  **/
  @Schema(description = "")
  public List<FilterCondition> getOr() {
    return or;
  }

  public void setOr(List<FilterCondition> or) {
    this.or = or;
  }

  public FilterCondition field(String field) {
    this.field = field;
    return this;
  }

   /**
   * Название поля
   * @return field
  **/
  @Schema(description = "Название поля")
  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  public FilterCondition op(String op) {
    this.op = op;
    return this;
  }

   /**
   * Операция
   * @return op
  **/
  @Schema(description = "Операция")
  public String getOp() {
    return op;
  }

  public void setOp(String op) {
    this.op = op;
  }

  public FilterCondition value(Object value) {
    this.value = value;
    return this;
  }

   /**
   * Значение. Для операций between ожидается массив из 2х элементов, для операции in - массив из любого количества элементов. Для операций. Для остальных операция ожидается строковое значение
   * @return value
  **/
  @Schema(description = "Значение. Для операций between ожидается массив из 2х элементов, для операции in - массив из любого количества элементов. Для операций. Для остальных операция ожидается строковое значение")
  public Object getValue() {
    return value;
  }

  public void setValue(Object value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterCondition filterCondition = (FilterCondition) o;
    return Objects.equals(this.and, filterCondition.and) &&
        Objects.equals(this.or, filterCondition.or) &&
        Objects.equals(this.field, filterCondition.field) &&
        Objects.equals(this.op, filterCondition.op) &&
        Objects.equals(this.value, filterCondition.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(and, or, field, op, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterCondition {\n");
    
    sb.append("    and: ").append(toIndentedString(and)).append("\n");
    sb.append("    or: ").append(toIndentedString(or)).append("\n");
    sb.append("    field: ").append(toIndentedString(field)).append("\n");
    sb.append("    op: ").append(toIndentedString(op)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
