/*
 * Copyright (c) 2020. Axetta LLC. All Rights Reserved.
 */

/*
 * API МЭШ.Контингент
 * Описание REST API МЭШ.Контингент
 *
 * OpenAPI spec version: 0.0.1
 * Contact: fixme@ktelabs.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.iteco.client.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.UUID;
/**
 * Песона
 */
@Schema(description = "Песона")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-28T06:28:05.879Z[GMT]")
public class Person {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("msr_id")
  private UUID msrId = null;

  @SerializedName("sso_id")
  private UUID ssoId = null;

  @SerializedName("contingent_id")
  private UUID contingentId = null;

  public Person id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Уникальный идентификатор персоны. Заполняется автоматически. При создании персоны заполнять 0000-0000-0000-0000
   * @return id
  **/
  @Schema(required = true, description = "Уникальный идентификатор персоны. Заполняется автоматически. При создании персоны заполнять 0000-0000-0000-0000")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public Person msrId(UUID msrId) {
    this.msrId = msrId;
    return this;
  }

   /**
   * Идентификатор МСР
   * @return msrId
  **/
  @Schema(description = "Идентификатор МСР")
  public UUID getMsrId() {
    return msrId;
  }

  public void setMsrId(UUID msrId) {
    this.msrId = msrId;
  }

  public Person ssoId(UUID ssoId) {
    this.ssoId = ssoId;
    return this;
  }

   /**
   * Идентификатор СУДИР
   * @return ssoId
  **/
  @Schema(description = "Идентификатор СУДИР")
  public UUID getSsoId() {
    return ssoId;
  }

  public void setSsoId(UUID ssoId) {
    this.ssoId = ssoId;
  }

  public Person contingentId(UUID contingentId) {
    this.contingentId = contingentId;
    return this;
  }

   /**
   * Идентификатор в системе-источнике
   * @return contingentId
  **/
  @Schema(description = "Идентификатор в системе-источнике")
  public UUID getContingentId() {
    return contingentId;
  }

  public void setContingentId(UUID contingentId) {
    this.contingentId = contingentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Person person = (Person) o;
    return Objects.equals(this.id, person.id) &&
        Objects.equals(this.msrId, person.msrId) &&
        Objects.equals(this.ssoId, person.ssoId) &&
        Objects.equals(this.contingentId, person.contingentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, msrId, ssoId, contingentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Person {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    msrId: ").append(toIndentedString(msrId)).append("\n");
    sb.append("    ssoId: ").append(toIndentedString(ssoId)).append("\n");
    sb.append("    contingentId: ").append(toIndentedString(contingentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
