/*
 * Copyright (c) 2020. Axetta LLC. All Rights Reserved.
 */

/*
 * API МЭШ.Контингент
 * Описание REST API МЭШ.Контингент
 *
 * OpenAPI spec version: 0.0.1
 * Contact: fixme@ktelabs.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.iteco.client.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.UUID;
import org.threeten.bp.OffsetDateTime;
/**
 * Адрес персоны
 */
@Schema(description = "Адрес персоны")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-07-28T06:28:05.879Z[GMT]")
public class PersonAddress {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("person_id")
  private UUID personId = null;

  @SerializedName("address_id")
  private Long addressId = null;

  @SerializedName("address_type_id")
  private Integer addressTypeId = null;

  @SerializedName("validation_state_id")
  private Integer validationStateId = null;

  @SerializedName("validated_at")
  private OffsetDateTime validatedAt = null;

  @SerializedName("actual_from")
  private OffsetDateTime actualFrom = null;

  @SerializedName("actual_to")
  private OffsetDateTime actualTo = null;

  @SerializedName("created_by")
  private UUID createdBy = null;

  @SerializedName("updated_by")
  private UUID updatedBy = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

  @SerializedName("address")
  private Address address = null;

  @SerializedName("address_type")
  private AddressType addressType = null;

  @SerializedName("validation_errors")
  private String validationErrors = null;

  public PersonAddress id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Идентификатор
   * @return id
  **/
  @Schema(required = true, description = "Идентификатор")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public PersonAddress personId(UUID personId) {
    this.personId = personId;
    return this;
  }

   /**
   * Идентификатор песоны
   * @return personId
  **/
  @Schema(description = "Идентификатор песоны")
  public UUID getPersonId() {
    return personId;
  }

  public void setPersonId(UUID personId) {
    this.personId = personId;
  }

  public PersonAddress addressId(Long addressId) {
    this.addressId = addressId;
    return this;
  }

   /**
   * Идентификатор адреса
   * @return addressId
  **/
  @Schema(description = "Идентификатор адреса")
  public Long getAddressId() {
    return addressId;
  }

  public void setAddressId(Long addressId) {
    this.addressId = addressId;
  }

  public PersonAddress addressTypeId(Integer addressTypeId) {
    this.addressTypeId = addressTypeId;
    return this;
  }

   /**
   * Тип адреса (каталог НСИ3 &lt;a href&#x3D;\&quot;https://wiki.edu.mos.ru/pages/viewpage.action?pageId&#x3D;18393747\&quot;&gt;RESIDENCE_FORM&lt;/href&gt;)
   * @return addressTypeId
  **/
  @Schema(required = true, description = "Тип адреса (каталог НСИ3 <a href=\"https://wiki.edu.mos.ru/pages/viewpage.action?pageId=18393747\">RESIDENCE_FORM</href>)")
  public Integer getAddressTypeId() {
    return addressTypeId;
  }

  public void setAddressTypeId(Integer addressTypeId) {
    this.addressTypeId = addressTypeId;
  }

  public PersonAddress validationStateId(Integer validationStateId) {
    this.validationStateId = validationStateId;
    return this;
  }

   /**
   * Статус проверки
   * @return validationStateId
  **/
  @Schema(description = "Статус проверки")
  public Integer getValidationStateId() {
    return validationStateId;
  }

  public void setValidationStateId(Integer validationStateId) {
    this.validationStateId = validationStateId;
  }

  public PersonAddress validatedAt(OffsetDateTime validatedAt) {
    this.validatedAt = validatedAt;
    return this;
  }

   /**
   * Дата проверки
   * @return validatedAt
  **/
  @Schema(description = "Дата проверки")
  public OffsetDateTime getValidatedAt() {
    return validatedAt;
  }

  public void setValidatedAt(OffsetDateTime validatedAt) {
    this.validatedAt = validatedAt;
  }

  public PersonAddress actualFrom(OffsetDateTime actualFrom) {
    this.actualFrom = actualFrom;
    return this;
  }

   /**
   * Дата и время начала действия связи
   * @return actualFrom
  **/
  @Schema(description = "Дата и время начала действия связи")
  public OffsetDateTime getActualFrom() {
    return actualFrom;
  }

  public void setActualFrom(OffsetDateTime actualFrom) {
    this.actualFrom = actualFrom;
  }

  public PersonAddress actualTo(OffsetDateTime actualTo) {
    this.actualTo = actualTo;
    return this;
  }

   /**
   * Дата и время окончания действия связи
   * @return actualTo
  **/
  @Schema(description = "Дата и время окончания действия связи")
  public OffsetDateTime getActualTo() {
    return actualTo;
  }

  public void setActualTo(OffsetDateTime actualTo) {
    this.actualTo = actualTo;
  }

  public PersonAddress createdBy(UUID createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Идентификатор системы-источника, создавшую запись
   * @return createdBy
  **/
  @Schema(description = "Идентификатор системы-источника, создавшую запись")
  public UUID getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(UUID createdBy) {
    this.createdBy = createdBy;
  }

  public PersonAddress updatedBy(UUID updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Идентификатор системы-источника, изменившую запись
   * @return updatedBy
  **/
  @Schema(description = "Идентификатор системы-источника, изменившую запись")
  public UUID getUpdatedBy() {
    return updatedBy;
  }

  public void setUpdatedBy(UUID updatedBy) {
    this.updatedBy = updatedBy;
  }

  public PersonAddress createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Дата и время создания
   * @return createdAt
  **/
  @Schema(description = "Дата и время создания")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public PersonAddress updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Дата и время изменения
   * @return updatedAt
  **/
  @Schema(description = "Дата и время изменения")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public PersonAddress address(Address address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @Schema(description = "")
  public Address getAddress() {
    return address;
  }

  public void setAddress(Address address) {
    this.address = address;
  }

  public PersonAddress addressType(AddressType addressType) {
    this.addressType = addressType;
    return this;
  }

   /**
   * Get addressType
   * @return addressType
  **/
  @Schema(description = "")
  public AddressType getAddressType() {
    return addressType;
  }

  public void setAddressType(AddressType addressType) {
    this.addressType = addressType;
  }

  public PersonAddress validationErrors(String validationErrors) {
    this.validationErrors = validationErrors;
    return this;
  }

   /**
   * Ошибки валидации из внешних систем
   * @return validationErrors
  **/
  @Schema(description = "Ошибки валидации из внешних систем")
  public String getValidationErrors() {
    return validationErrors;
  }

  public void setValidationErrors(String validationErrors) {
    this.validationErrors = validationErrors;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonAddress personAddress = (PersonAddress) o;
    return Objects.equals(this.id, personAddress.id) &&
        Objects.equals(this.personId, personAddress.personId) &&
        Objects.equals(this.addressId, personAddress.addressId) &&
        Objects.equals(this.addressTypeId, personAddress.addressTypeId) &&
        Objects.equals(this.validationStateId, personAddress.validationStateId) &&
        Objects.equals(this.validatedAt, personAddress.validatedAt) &&
        Objects.equals(this.actualFrom, personAddress.actualFrom) &&
        Objects.equals(this.actualTo, personAddress.actualTo) &&
        Objects.equals(this.createdBy, personAddress.createdBy) &&
        Objects.equals(this.updatedBy, personAddress.updatedBy) &&
        Objects.equals(this.createdAt, personAddress.createdAt) &&
        Objects.equals(this.updatedAt, personAddress.updatedAt) &&
        Objects.equals(this.address, personAddress.address) &&
        Objects.equals(this.addressType, personAddress.addressType) &&
        Objects.equals(this.validationErrors, personAddress.validationErrors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, personId, addressId, addressTypeId, validationStateId, validatedAt, actualFrom, actualTo, createdBy, updatedBy, createdAt, updatedAt, address, addressType, validationErrors);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonAddress {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    personId: ").append(toIndentedString(personId)).append("\n");
    sb.append("    addressId: ").append(toIndentedString(addressId)).append("\n");
    sb.append("    addressTypeId: ").append(toIndentedString(addressTypeId)).append("\n");
    sb.append("    validationStateId: ").append(toIndentedString(validationStateId)).append("\n");
    sb.append("    validatedAt: ").append(toIndentedString(validatedAt)).append("\n");
    sb.append("    actualFrom: ").append(toIndentedString(actualFrom)).append("\n");
    sb.append("    actualTo: ").append(toIndentedString(actualTo)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    addressType: ").append(toIndentedString(addressType)).append("\n");
    sb.append("    validationErrors: ").append(toIndentedString(validationErrors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
