//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.30 at 05:41:38 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.msk.ru/uec/TransactionSynchronization/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.msk.schemas.uec.transactionsynchronization.v1;
