/*
 * Copyright (c) 2020. Axetta LLC. All Rights Reserved.
 */

/*
 * API МЭШ.Контингент
 * Описание REST API МЭШ.Контингент
 *
 * OpenAPI spec version: 0.0.1
 * Contact: fixme@ktelabs.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.iteco.client.api;

import ru.iteco.client.ApiException;
import ru.iteco.client.model.ModelClass;

import org.threeten.bp.OffsetDateTime;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for ClassApi
 */
@Ignore
public class ClassApiTest {

    private final ClassApi api = new ClassApi();

    /**
     * Создать класс
     *
     * Метод создания класса
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addClassTest() throws ApiException {
        ModelClass body = null;
        ModelClass response = api.addClass(body);

        // TODO: test validations
    }
    /**
     * Поиск классов
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void classesGetTest() throws ApiException {
        String filter = null;
        String expand = null;
        String top = null;
        String skip = null;
        String orderby = null;
        OffsetDateTime actualOn = null;
        List<ModelClass> response = api.classesGet(filter, expand, top, skip, orderby, actualOn);

        // TODO: test validations
    }
    /**
     * Удаление класса
     *
     * Помечает класс как удаленный
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteClassTest() throws ApiException {
        String id = null;
        api.deleteClass(id);

        // TODO: test validations
    }
    /**
     * Получить класс по идентификатору
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getClassByIdTest() throws ApiException {
        UUID id = null;
        ModelClass response = api.getClassById(id);

        // TODO: test validations
    }
    /**
     * Обновить описание созданного класса
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateClassTest() throws ApiException {
        ModelClass body = null;
        String id = null;
        ModelClass response = api.updateClass(body, id);

        // TODO: test validations
    }
}
