/*
 * Copyright (c) 2020. Axetta LLC. All Rights Reserved.
 */

/*
 * API МЭШ.Контингент
 * Описание REST API МЭШ.Контингент
 *
 * OpenAPI spec version: 0.0.1
 * Contact: fixme@ktelabs.ru
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ru.iteco.client.api;

import ru.iteco.client.ApiException;
import ru.iteco.client.model.Category;

import org.threeten.bp.LocalDate;
import ru.iteco.client.model.ModelClass;
import org.threeten.bp.OffsetDateTime;
import ru.iteco.client.model.PersonInfo;

import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for SearchApi
 */
@Ignore
public class SearchApiTest {

    private final SearchApi api = new SearchApi();

    /**
     * Поиск классов
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void classesGetTest() throws ApiException {
        String filter = null;
        String expand = null;
        String top = null;
        String skip = null;
        String orderby = null;
        OffsetDateTime actualOn = null;
        List<ModelClass> response = api.classesGet(filter, expand, top, skip, orderby, actualOn);

        // TODO: test validations
    }
    /**
     * Поиск категории
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCategoriesTest() throws ApiException {
        String filter = null;
        String top = null;
        String skip = null;
        String orderby = null;
        List<Category> response = api.getCategories(filter, top, skip, orderby);

        // TODO: test validations
    }
    /**
     * Поиск персон
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void personsGetTest() throws ApiException {
        String filter = null;
        String expand = null;
        String top = null;
        String skip = null;
        String orderby = null;
        OffsetDateTime actualOn = null;
        LocalDate trainingOn = null;
        List<PersonInfo> response = api.personsGet(filter, expand, top, skip, orderby, actualOn, trainingOn);

        // TODO: test validations
    }
}
