
package ru.axetta.soap.smev;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MsgExamplePort", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MsgExamplePort {


    /**
     * 
     * @param smevHeader
     * @param parameters
     * @return
     *     returns ru.axetta.soap.smev.SyncResponseType
     */
    @WebMethod(action = "http://smev.gosuslugi.ru/MsgExample/syncReq")
    @WebResult(name = "SyncResponse", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
    public SyncResponseType syncReq(
        @WebParam(name = "Header", targetNamespace = "http://smev.gosuslugi.ru/rev110801", header = true, partName = "smevHeader")
        HeaderType smevHeader,
        @WebParam(name = "SyncRequest", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
        SyncRequestType parameters);

    /**
     * 
     * @param smevHeader
     * @param parameters
     * @return
     *     returns ru.axetta.soap.smev.SyncResponseType
     */
    @WebMethod(action = "http://smev.gosuslugi.ru/MsgExample/aSyncReq")
    @WebResult(name = "aSyncReqResponse", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
    public SyncResponseType aSyncReq(
        @WebParam(name = "Header", targetNamespace = "http://smev.gosuslugi.ru/rev110801", header = true, partName = "smevHeader")
        HeaderType smevHeader,
        @WebParam(name = "aSyncReqRequest", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
        SyncRequestType parameters);

    /**
     * 
     * @param smevHeader
     * @param parameters
     * @return
     *     returns ru.axetta.soap.smev.SyncResponseType
     */
    @WebMethod(action = "http://smev.gosuslugi.ru/MsgExample/aSyncResult")
    @WebResult(name = "aSyncResultResponse", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
    public SyncResponseType aSyncResult(
        @WebParam(name = "Header", targetNamespace = "http://smev.gosuslugi.ru/rev110801", header = true, partName = "smevHeader")
        HeaderType smevHeader,
        @WebParam(name = "aSyncResultRequest", targetNamespace = "http://smev.gosuslugi.ru/MsgExample/xsd/types", partName = "parameters")
        SyncRequestType parameters);

}
