
package ru.axetta.ecafe.processor.dashboard;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DashboardService", targetNamespace = "http://dashboard.processor.ecafe.axetta.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DashboardService {


    /**
     * 
     * @return
     *     returns ru.axetta.ecafe.processor.dashboard.DashboardResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfoForDashboard", targetNamespace = "http://dashboard.processor.ecafe.axetta.ru/", className = "ru.axetta.ecafe.processor.dashboard.GetInfoForDashboard")
    @ResponseWrapper(localName = "getInfoForDashboardResponse", targetNamespace = "http://dashboard.processor.ecafe.axetta.ru/", className = "ru.axetta.ecafe.processor.dashboard.GetInfoForDashboardResponse")
    public DashboardResponse getInfoForDashboard();

}
